version: '3.1'
name: postgres
services:
  postgres:
    container_name: postgres
    image: gugajedi/postgres-14.5-alpine:latest
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=LATIN1 --locale=C /var/lib/postgresql/data'
      TZ: America/Sao_Paulo
    volumes:
      - ./pg_data/:/var/lib/postgresql/data/:rw
      - ./utils/:/utils/:rw
      - ./backup/:/backup/:rw
    ports:
      - 5432:5432
    networks:
      - geek.net
networks:
  geek.net:
    name: geek.net
    driver: bridge